### ISSUE TITLE
Unexpected Results using Incrementality

### ISSUE THREAD

**Issue by OliverMa1** [VeriFIT/z3-noodler#196]
If you run

```
(declare-fun X () String)
(push 1)
(assert (str.in_re X (re.* (re.union (str.to_re "n") (str.to_re "t")))))
(declare-fun Y () String)
(declare-fun A () String)
(declare-fun B () String)
(assert (and true     (= Y (str.++ A "tn" B))     (= X (str.++ A "nt" B))     (str.in_re A (re.* (str.to_re "n")))     (str.in_re B (re.* (str.to_re "n")))))
(assert (= Y "tn"))
(check-sat)
(get-model)
(assert (distinct X "nt"))
(check-sat)
(get-model)
```

It should return unsat for the second (check-sat) but it returns a model with X = "nt". (This was discovered calling z3-noodler -in)

**Comment by vhavlena** [comment]
Hi OliverMa1,
thank you for letting us know. We look at it as soon as possible.

**Comment by OliverMa1** [comment]
Hi, after some more experiments, we concluded that it is not the incrementality, but perhaps the distinct/!=.
See the following code which should be unsat (tested with z3):

```
(declare-fun X () String)
(assert (let ((a!1 (re.union (re.union (re.union (str.to_re "E") (str.to_re "T"))
                               (str.to_re "R"))
                     (str.to_re "L"))))
  (str.in_re X (re.* a!1))))
(assert (let ((a!1 (re.++ (re.* (re.++ (str.to_re "L") (str.to_re "L")))
                  (str.to_re "L")))
      (a!4 (re.++ (re.* (re.++ (str.to_re "L") (str.to_re "L")))
                  (re.++ (str.to_re "L") (str.to_re "R")))))
(let ((a!2 (re.union (str.to_re "L")
                     (re.++ (re.++ (str.to_re "L") (str.to_re "L")) a!1)))
      (a!5 (re.union (re.++ (str.to_re "L") (str.to_re "R"))
                     (re.++ (re.++ (str.to_re "L") (str.to_re "L")) a!4))))
(let ((a!3 (re.++ (re.* (re.++ (str.to_re "L") (str.to_re "L"))) a!2))
      (a!6 (re.++ (re.* (re.++ (str.to_re "L") (str.to_re "L"))) a!5)))
(let ((a!7 (re.union (re.++ (str.to_re "R") (str.to_re "R"))
                     (re.++ (re.++ (str.to_re "R") (str.to_re "L")) a!6)))
      (a!8 (re.union (str.to_re "R")
                     (re.++ (re.++ (str.to_re "R") (str.to_re "L")) a!3))))
(let ((a!9 (re.union a!8 (re.++ a!7 (re.++ (re.* a!7) a!8)))))
(let ((a!10 (re.++ (re.union (str.to_re "R") (re.++ (str.to_re "L") a!6))
                   (re.++ (re.* a!7) a!9))))
(let ((a!11 (re.union (re.union (str.to_re "") (re.++ (str.to_re "L") a!3))
                      a!10)))
  (and (str.in_re X a!11) true)))))))))
(assert (let ((a!1 (re.union (re.union (re.union (str.to_re "T") (str.to_re "L"))
                               (str.to_re "R"))
                     (str.to_re "E"))))
  (str.in_re X (re.++ a!1 a!1))))
(check-sat)
(get-model)
(assert (not(= X "LL")))
(check-sat)
(get-model)
(assert (not(= X "RR")))
(check-sat)
(get-model)
```

**Comment by jurajsic** [comment]
Hi, thank you for another example.
You were right the first time, the problem is with incrementality, more specifically, if some `(check-sat)` returns `sat`, then all following `(check-sat)` will also return `sat`.
I am working on the fix right now.

**Comment by jurajsic** [comment]
Hi, this should be fixed now.

However, we did not really try incremental solving, so there might be a lot more bugs. If you find any please let us know :)

**Comment by hongjianjiang** [comment]
Hi, I think the problem still exists in the newest version of z3-noodler.

**Comment by jurajsic** [comment]
Hi, thanks for letting us know, it seems that the fix in #197 was not complete fix, but it should be fixed now by #215.
The version in `devel` should work correctly, if not please let us know.
